name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
      PUBLIC_PATH: ${{ vars.PUBLIC_PATH }} # Example: "/ts-news-app/"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn install

      - name: Build app with env vars
        run: |
          echo "API_KEY=$API_KEY" > .env
          yarn build
        env:
          PUBLIC_PATH: ${{ env.PUBLIC_PATH }}
          API_KEY: ${{ env.API_KEY }}

      - name: Add 404 fallback for Vue Router
        run: cp dist/spa/index.html dist/spa/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/spa
          user_name: github-actions
          user_email: github-actions@github.com
